services:
  - type: web
    name: crypto-vault
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crypto_vault_db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: crypto_vault_db
    databaseName: crypto_vault
    user: crypto_vault_user